import Head from 'next/head'
import tw from 'twin.macro'
import PasswordGen from '../components/passwordGen'

const IndexPage = () => (
  <div>
    <Head>
      <title>Frontend Mentor | Expenses Chart Component</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/images/favicon-32x32.png" />
    </Head>
    <div tw="flex items-center justify-center min-h-screen bg-vdGrey">
      <PasswordGen />
    </div>
  </div>
)

export default IndexPage
